2024-01-03 22:50:15 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DF0B967EC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:50:15 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DF0B9171C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:50:15 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DF0B9679C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:50:15 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DF0B983408>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:50:15 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DF0B983608>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:50:15 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001DF0B983B48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:54:43 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016259712F88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:54:43 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000162597D7A08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:54:43 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000162597D7408>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:54:43 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000162596D14C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:54:43 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000162597D7288>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:54:43 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016259741448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:57:43 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025DDA058E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:57:43 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025DDA046C08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:57:43 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025DDA007848>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:57:43 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025DDA073588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:57:43 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025DDA073888>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-03 22:57:43 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025DDA073D08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:13:10 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EC0649D448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:13:10 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EC0649D988>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:13:10 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EC0649F208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:13:10 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EC0649FA08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:13:10 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EC0649FF08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:13:10 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EC064B9408>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:16:14 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E555AE0188>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:16:14 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E556474A88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:16:14 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E5564C9CC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:16:14 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E5564E63C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:16:14 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E5564E6548>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 12:16:14 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E5564E6A88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:25:00 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ECD9182A48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:25:00 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ECD92281C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:25:00 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ECD9228B48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:25:00 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ECD91CF288>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:25:00 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ECD9231B48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:25:00 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ECD9231088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:30:44 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CC75CE1248>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:30:44 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CC75D48248>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:30:44 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CC75D57AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:30:44 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CC75D07388>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:30:44 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CC75D85408>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-04 16:30:44 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CC75D85948>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:15:31 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000252EFD67C88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:15:31 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000252EFD67648>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:15:31 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000252EFDB7D08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:15:31 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000252EFDF5408>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:15:31 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000252EFDF55C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:15:31 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000252EFDF5B08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:17:40 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000176DE49B488>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:17:40 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000176DE4C2108>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:17:40 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000176DE4C2E88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:17:40 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000176DE4C0E08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:17:40 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000176DE4C0B08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 10:17:40 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000176DE4C0688>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 11:27:14 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023DD87485C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 11:27:14 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023DD8748AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 11:27:14 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023DD8757F88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 11:27:14 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023DD8775408>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 11:27:14 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023DD8775608>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-08 11:27:14 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023DD8775B48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:48:55 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CDCF2A7708>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:48:55 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CDCF2A75C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:48:55 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CDCF2F9988>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:48:55 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CDCF315408>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:48:55 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CDCF315508>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:48:55 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CDCF315A88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:49:59 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C294EC6448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:49:59 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C294E574C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:49:59 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C294ED7908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:49:59 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C294EF4208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:49:59 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C294EF4888>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 16:49:59 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C294EF4D08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:16:54 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000234C6547648>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:16:54 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000234C6586EC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:16:54 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000234C6597D88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:16:54 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000234C65B4448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:16:54 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000234C65B4708>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:16:54 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000234C65B4B88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:23:40 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002845BF68C88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:23:40 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002845BF39308>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:23:40 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002845BF36A88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:23:40 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002845BF36C48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:23:40 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002845BF56288>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-10 17:23:40 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002845BF73F08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-20 10:24:19 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028E840B7B48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-20 10:24:19 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028E840B75C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-20 10:24:19 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028E84105EC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-20 10:24:19 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028E84124408>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-20 10:24:19 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028E84124608>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2024-01-20 10:24:19 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028E84124B48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
